# App
spring.application.name=urlify

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/urlify_db
spring.datasource.username=vickyshetty
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache
spring.cache.type=redis
spring.cache.redis.time-to-live=86400000

# Server
server.port=8080

# Async
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10